### PR TITLE
Adding method for Microsoft

### PR DESCRIPTION
**Pull request by NoohPeePee**
Error on reading url from table data. :(

### CODE REVIEW

**Comment by NoohPeePee** [comment]
Done - (Optimization Required -- Will be added later)

**Comment by NoohPeePee** [comment]
`    def scrape_microsoft(self, url):
        ''' This method is used for parsing https://technet.microsoft.com/en-us/security/advisories'''
        data = self.get_html_data(url)      # souping
        table_data = data.find('div', class_="", id="sec_advisory") # identifying the required tag
        for row in table_data.find_all('tr')[1:10]:   # Iterating through advisory column 
            temp_data = deepcopy(self.value)                # creating copy of self.value
            colomns = row.find_all('td')
            temp_data['date'] = colomns[0].text.strip()
            temp_data['val_name'] = colomns[2].text.strip()
            page_link = colomns[2].find('a').get('href')    # child link to advisory
            new_data = self.get_html_data(page_link)    # souping

            temp_data['description'] = new_data.find("div", id="mainBody").find_all('p')[2].text    
            if new_data.find("table", summary="table"):     # checking for tables
                table = new_data.find("table", summary="table") # table datas
                table_rows = len(table.find_all('tr'))  # validating
                i = 2
                if(table_rows > 2):
                    affected_products = ''
                    for i in range(table_rows): # iterating for all affected products list
                        if(table.find_all('tr')[i].p):
                            product = table.find_all('tr')[i].p.text.strip()
                            affected_products = '{}\n{}'.format(affected_products, product)
                            temp_data['affected'] = affected_products # Only final value is getting written

            self.data.append(temp_data) # appending temp data info to class variable called self.data
`

**Comment by shamlikt** [comment]
Nice work

**Comment by NoohPeePee** [comment]
Optimized final Object - scrape_microsoft(self, url) below:

`
    def scrape_microsoft(self, url):
        ''' This method is used for parsing https://technet.microsoft.com/en-us/security/advisories'''
        data = self.get_html_data(url)      # souping
        table_data = data.find('div', class_="", id="sec_advisory") # identifying the required tag
        for row in table_data.find_all('tr')[1:10]:   # Iterating through advisory column 
            temp_data = deepcopy(self.value)                # creating copy of self.value
            colomns = row.find_all('td')
            temp_data['date'] = colomns[0].text.strip()
            temp_data['val_name'] = colomns[2].text.strip()
            temp_data['severity'] = "Medium"
            page_link = colomns[2].find('a').get('href')    # child link to advisory
            new_data = self.get_html_data(page_link)    # souping

            temp_data['description'] = new_data.find("div", id="mainBody").find_all('p')[2].text    
            if new_data.find("table", summary="table"):     # checking for tables
                table = new_data.find("table", summary="table") # table datas
                table_rows = len(table.find_all('tr'))  # validating
                if(table_rows > 2):
                    affected_products = ''
                    for i in range(2,table_rows): # iterating for all affected products list
                        if(table.find_all('tr')[i].p):
                            product = table.find_all('tr')[i].p.text.strip()
                            affected_products = '{}\n{}'.format(affected_products, product)
                            temp_data['affected'] = affected_products # Only final value is getting written
                            
            temp_data['solution'] = "You will need to fix both direct dependencies and review and fix any transitive dependencies. "
            self.data.append(temp_data) # appending temp data info to class variable called self.data
`

**Comment by NoohPeePee** [comment]
any updates.. ?? :(


Best Regards,

Nooh Ibrahim
Cloud Specialist
+97433312041 (Doha)
+919633195109 (India)

**Comment by NoohPeePee** [comment]
I am unable to fetch table from
https://kb.juniper.net/InfoCenter/index?page=content&channel=SECURITY_ADVISORIES&cat=SIRT_1&sort=datemodified&&actp=&dir=descending&max=1000&batch=15&rss=true

It is just taking first tr/td/th only..!! Why is it ??



Best Regards,

Nooh Ibrahim
Cloud Specialist
+97433312041 (Doha)
+919633195109 (India)

**Pull request merged**
